export { CopilotStep } from './components/CopilotStep'
export { copilot, CopilotOptionProps } from './hocs/copilot'
export { TourGuideZone } from './components/TourGuideZone'
export { TooltipProps } from './components/Tooltip'
export { TourGuideZoneByPosition } from './components/TourGuideZoneByPosition'
export { CopilotWrapper } from './components/CopilotWrapper'
export * from './types'
